name: easy_color_picker
description: Simple but flexible color picker to help you handle color selection
version: 1.0.0
homepage: https://github.com/4inka/flutter_easy_color_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
